src/Common/UserBundle/Entity/User.php
<?php

namespace Common\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="Common\UserBundle\Repository\UserRepository")
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * 
 * @UniqueEntity(fields={"email"}, message="Ten email jest już zajęty.")
 */
class User implements AdvancedUserInterface, \Serializable {
	/**
	 * @ORM\Column(type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * 
	 * 
	 * @Assert\Length(
	 *      min=0,
	 *      max=20,
	 *      groups = {"Registration", "ChangeDetails"}
	 * )
	 * @Assert\Length(
	 *      max = 20,
	 *      maxMessage = "Maksymalnie {{ limit }} znaków"
	 * )
	 */
	private $username;

	/**
	 * @ORM\Column(type="string", length = 120, unique = true)
	 * 
	 * @Assert\NotBlank(
	 *      groups = {"Registration"}
	 * )
	 * 
	 * @Assert\Email(
	 *      groups = {"Registration"}
	 * )
	 * 
	 * @Assert\Length(
	 *      max = 40,
	 *      maxMessage = "Maksymalnie {{ limit }} znaków"
	 * )
	 */
	private $email;

	/**
	 * @ORM\Column(type="string", length = 64)
	 */
	private $password;

	/**
	 * @Assert\NotBlank(
	 * )
	 * 
	 * @Assert\Length(
	 *      min=6,
	 *      max=64,
	 *      minMessage = "Minimalnie {{ limit }} znaków",
	 *      maxMessage = "Maksymalnie {{ limit }} znaków"
	 * )
	 */
	private $plainPassword;

	/**
	 * @ORM\Column(name="account_non_expired", type="boolean")
	 */
	private $accountNonExpired = true;

	/**
	 * @ORM\Column(name="account_non_locked", type="boolean")
	 */
	private $accountNonLocked = true;

	/**
	 * @ORM\Column(name="credentials_non_expired", type="boolean")
	 */
	private $credentialsNonExpired = true;

	/**
	 * @ORM\Column(type="boolean")
	 */
	private $enabled = false;

	/**
	 * @ORM\Column(type="array")
	 */
	private $roles;

	/**
	 * @ORM\Column(name="action_token", type="string", length = 20, nullable = true)
	 */
	private $actionToken;

	/**
	 * @ORM\Column(name="register_date", type="datetime")
	 */
	private $registerDate;

	

	/**
	 * @ORM\Column(type="datetime", nullable = true)
	 */
	private $updateDate;

	public function eraseCredentials() {
		$this->plainPassword = null;
	}

	public function getPassword() {
		return $this->password;
	}

	public function getRoles() {
		if (empty($this->roles)) {
			return array('ROLE_USER');
		}

		return $this->roles;
	}

	public function getSalt() {
		return null;
	}

	public function getUsername() {
		return $this->username;
	}

	public function isAccountNonExpired() {
		return $this->accountNonExpired;
	}

	public function isAccountNonLocked() {
		return $this->accountNonLocked;
	}

	public function isCredentialsNonExpired() {
		return $this->credentialsNonExpired;
	}

	public function isEnabled() {
		return $this->enabled;
	}

//put your code here

	function __construct() {
		$this->registerDate = new \DateTime();
	}

	/**
	 * Get id
	 *
	 * @return integer 
	 */
	public function getId() {
		return $this->id;
	}

	/**
	 * Set username
	 *
	 * @param string $username
	 * @return User
	 */
	public function setUsername($username) {
		$this->username = $username;

		return $this;
	}

	/**
	 * Set email
	 *
	 * @param string $email
	 * @return User
	 */
	public function setEmail($email) {
		$this->email = $email;

		return $this;
	}

	/**
	 * Get email
	 *
	 * @return string 
	 */
	public function getEmail() {
		return $this->email;
	}

	/**
	 * Set password
	 *
	 * @param string $password
	 * @return User
	 */
	public function setPassword($password) {
		$this->password = $password;

		return $this;
	}

	/**
	 * Set accountNonExpired
	 *
	 * @param boolean $accountNonExpired
	 * @return User
	 */
	public function setAccountNonExpired($accountNonExpired) {
		$this->accountNonExpired = $accountNonExpired;

		return $this;
	}

	/**
	 * Get accountNonExpired
	 *
	 * @return boolean 
	 */
	public function getAccountNonExpired() {
		return $this->accountNonExpired;
	}

	/**
	 * Set accountNonLocked
	 *
	 * @param boolean $accountNonLocked
	 * @return User
	 */
	public function setAccountNonLocked($accountNonLocked) {
		$this->accountNonLocked = $accountNonLocked;

		return $this;
	}

	/**
	 * Get accountNonLocked
	 *
	 * @return boolean 
	 */
	public function getAccountNonLocked() {
		return $this->accountNonLocked;
	}

	/**
	 * Set credentialsNonExpired
	 *
	 * @param boolean $credentialsNonExpired
	 * @return User
	 */
	public function setCredentialsNonExpired($credentialsNonExpired) {
		$this->credentialsNonExpired = $credentialsNonExpired;

		return $this;
	}

	/**
	 * Get credentialsNonExpired
	 *
	 * @return boolean 
	 */
	public function getCredentialsNonExpired() {
		return $this->credentialsNonExpired;
	}

	/**
	 * Set enabled
	 *
	 * @param boolean $enabled
	 * @return User
	 */
	public function setEnabled($enabled) {
		$this->enabled = $enabled;

		return $this;
	}

	/**
	 * Get enabled
	 *
	 * @return boolean 
	 */
	public function getEnabled() {
		return $this->enabled;
	}

	/**
	 * Set roles
	 *
	 * @param array $roles
	 * @return User
	 */
	public function setRoles($roles) {
		$this->roles = $roles;

		return $this;
	}

	/**
	 * Set actionToken
	 *
	 * @param string $actionToken
	 * @return User
	 */
	public function setActionToken($actionToken) {
		$this->actionToken = $actionToken;

		return $this;
	}

	/**
	 * Get actionToken
	 *
	 * @return string 
	 */
	public function getActionToken() {
		return $this->actionToken;
	}

	/**
	 * Set registerDate
	 *
	 * @param \DateTime $registerDate
	 * @return User
	 */
	public function setRegisterDate($registerDate) {
		$this->registerDate = $registerDate;

		return $this;
	}

	/**
	 * Get registerDate
	 *
	 * @return \DateTime 
	 */
	public function getRegisterDate() {
		return $this->registerDate;
	}

	public function serialize() {
		return serialize(array(
			$this->id,
			$this->username,
			$this->password
		));
	}

	public function unserialize($serialized) {
		list(
				$this->id,
				$this->username,
				$this->password
				) = unserialize($serialized);
	}

	public function getPlainPassword() {
		return $this->plainPassword;
	}

	public function setPlainPassword($plainPassword) {
		$this->plainPassword = $plainPassword;
	}

	public function setAccountExpired($accountNonExpired) {
		$this->accountNonExpired = !$accountNonExpired;

		return $this;
	}

	public function getAccountExpired() {
		return !$this->accountNonExpired;
	}

	public function setAccountLocked($accountNonLocked) {
		$this->accountNonLocked = !$accountNonLocked;

		return $this;
	}

	public function getAccountLocked() {
		return !$this->accountNonLocked;
	}

	public function setCredentialsExpired($credentialsNonExpired) {
		$this->credentialsNonExpired = !$credentialsNonExpired;

		return $this;
	}

	public function getCredentialsExpired() {
		return !$this->credentialsNonExpired;
	}

	/**
	 * Set updateDate
	 *
	 * @param \DateTime $updateDate
	 *
	 * @return User
	 */
	public function setUpdateDate($updateDate) {
		$this->updateDate = $updateDate;

		return $this;
	}

	/**
	 * Get updateDate
	 *
	 * @return \DateTime
	 */
	public function getUpdateDate() {
		return $this->updateDate;
	}

}

src/Common/UserBundle/Resources/views/Admin/form.html.twig
{% extends 'AirAdminBundle::base.html.twig' %}

{% block pageTitle %}
    {{ parent() }} - Profil użytkownika "{{ user.username }}"
{% endblock %}

{% block content %}
<div class="container">
    {{ form_start(form) }}
        <div class="row">
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Dane podstawowe
                    </div>
                    <div class="panel-body">
                        {{ form_row(form.username) }}
                        {{ form_row(form.email) }}
                        {{ form_row(form.roles, {'attr': {'class': 'select-block'}}) }}
                    </div>
                </div>
            </div> <!-- .col-md-8 -->

            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Akcje
                            </div>
                            <div class="panel-body">
                                <button class="btn btn-success">Zapisz</button>
                            </div>
                        </div>
                    </div>  <!-- .col-md-12 -->

                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Dostepność
                            </div>
                            <div class="panel-body account-checkbox">
                                {% set labelWidth = 9 %}
                                {% set wrapperWidth = 3 %}
                                {{ form_row(form.accountExpired, {'label_length': labelWidth, 'wrapper_length': wrapperWidth}) }}
                                {{ form_row(form.accountLocked, {'label_length': labelWidth, 'wrapper_length': wrapperWidth}) }}
                                {{ form_row(form.credentialsExpired, {'label_length': labelWidth, 'wrapper_length': wrapperWidth}) }}
                                {{ form_row(form.enabled, {'label_length': labelWidth, 'wrapper_length': wrapperWidth}) }}
                            </div> <!-- .panel-body -->
                        </div> <!-- .panel -->
                    </div> <!-- .col-md-12 -->
                </div> <!-- .row -->
            </div> <!-- .col-md-4 -->
        </div> <!-- .row -->
        
        {{ form_rest(form) }}
    {{ form_end(form) }}
</div> <!-- .container -->
{% endblock %}

src/Common/UserBundle/Resources/views/Admin/index.html.twig
{% extends 'AirAdminBundle::base.html.twig' %}

{% block pageTitle %}
	{{ parent() }} - Posty
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    Użytkownicy
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    {#
                                    <th>ID</th>
                                    <th><a class="sortable" href="#">Imie i nazwisko</a></th>
                                    <th><a class="sortable sort-desc" href="#">Nick</a></th>
                                    <th><a class="sortable sort-asc" href="#">Email</a></th>
                                    <th><a class="sortable" href="#">Data rejestracji</a></th>
                                    #}
                                    <th>{{ knp_pagination_sortable(pagination, 'Id', 'u.id') }}</th>
                                    <th>{{ knp_pagination_sortable(pagination, 'Nick', 'u.username') }}</th>
                                    <th>{{ knp_pagination_sortable(pagination, 'Email', 'u.email') }}</th>
                                    <th>{{ knp_pagination_sortable(pagination, 'Data rejestracji', 'u.registerDate') }}</th>
                                    <th>Akcje</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in pagination %}
                                    {% set formPath = path('user_adminUserForm', {'id': user.id}) %}
                                <tr>
                                    <td>{{ user.id }}</td>
                                    <td><a href="{{ formPath }}">{{ user.username }}</a></td>
                                    <td>{{ user.email }}</td>
                                    <td>{{ user.registerDate|admin_format_date }}</td>
                                    <td>
                                        <a href="{{ formPath }}" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    
                    {{ knp_pagination_render(pagination, 'AirAdminBundle:Pagination:admin_pagination.html.twig') }}
                </div> <!-- .panel-body -->
            </div> <!-- .panel -->
        </div> <!-- .col-md-12 -->
    </div> <!-- .row -->
</div> <!-- .container -->
{% endblock %}